### DISCUSSION TITLE
Missing docker image for elyra/enterprise-gateway:3.2.2 on Dockerhub

### DISCUSSION THREAD

**Discussion by Chiragasourabh** [jupyter/enterprise_gateway#1287] [Q&A] [answered]
Hi @lresende,

I see that there is a new release of [enterprise-gateway v3.2.2] (https://github.com/jupyter-server/enterprise_gateway/releases/tag/v3.2.2) but the respective docker image for the release is not available in the docker hub yet. Is there any specific reason for not publishing the docker image? if not, when could an image for the release can be expected on the docker hub?

Thank you

**Comment by anujpb** [comment]
@kevin-bates Do you know if there was a reason why the docker image for enterprise gateway was not published?

**Comment by kevin-bates** [comment]
Hi @anujpb.  The image build process is still a manual process that takes quite a while but it does appear that some images (`elyra/enterprise-gateway`, `elyra/kernel-tf-py`, and `elyra/kernel-tf-gpu-py`) did not complete the build and fell through the cracks.  We apologize.

Since you've already pinged @lresende, I will ping him directly and see if he's able to complete the images for 3.2.2.

**Reply by lresende** [reply]
will re-run the build, sorry for the inconvenience...

**Comment by lresende** [comment, marked as answer]
Done, the `kerne-tf-gpu-py` for now is a problem to publish multi-arch, so I just publish x86.

**Comment by kevin-bates** [comment]
Thank you @lresende!

> the `kerne-tf-gpu-py` for now is a problem to publish multi-arch, so I just publish x86.

Yes, that sounds familiar - no problem.

**Comment by kevin-bates** [comment]
Just noticed we haven't closed any discussions so, when this is closed, it kinda falls off the current set of discussions - which feels unhelpful to folks - so I'm going to reopen until we decide to start closing discussions that warrant their closure.

**Reply by anujpb** [reply]
Sounds good. I see that the x86 variants of the `elyra/kernel-tf-py `and `elyra/kernel-tf-gpu-py` images haven't made it to docker hub yet. In the future, we probably will require those too.

For now, I am surely happy about the `elyra/enterprise-gateway` image. 
Many thanks to you @kevin-bates & @lresende.

**Comment by paf91** [comment]
@kevin-bates @lresende does look that now 3.2.3 images are missing after a month of 3.2.3 release

**Comment by lresende** [comment]
This was fixed, see https://github.com/jupyter-server/enterprise_gateway/issues/1371

**Reply by paf91** [reply]
![image](https://github.com/jupyter-server/enterprise_gateway/assets/12195041/a6ad01dc-9d85-4597-be03-3c12469dac02)
Unfortunately I'm not sure about that :(

**Comment by lresende** [comment]
I went to docker hub and it seems i built them all but never pushed, pushing them up now...

**Reply by paf91** [reply]
thanks. could you please also tell me how I can run spark 3 using this version? seems to support 2.4 only...

**Comment by lresende** [comment]
You should be able to run Spark 3 with this version/release

![image](https://github.com/jupyter-server/enterprise_gateway/assets/382917/4083e01e-cce7-4144-8ac7-59f710e7e92a)

**Comment by lresende** [comment]
Feel free to close if this solve your issues

**Reply by paf91** [reply]
im getting `exec /usr/bin/tini: exec format error `error using this image. what architecture it's using?

**Reply by paf91** [reply]
in the meantime 3.2.2 seem to start fine using (same command with 3.2.3 gives error `exec /usr/bin/tini: exec format error`)

```
helm  upgrade --install  enterprise-gateway \
  https://github.com/jupyter-server/enterprise_gateway/releases/download/v3.2.2/jupyter_enterprise_gateway_helm-3.2.2.tar.gz \
   --namespace enterprise-gateway \
   -f jupyter/gateway/values.yaml

```
values.yaml contents:
```
service:
  type: "ClusterIP"
  ports:
    # The primary port on which Enterprise Gateway is servicing requests.
    - name: "http"
      port: 8888
      targetPort: 8888
    # The  port on which Enterprise Gateway will receive kernel connection info responses.
    - name: "http-response"
      port: 8877
      targetPort: 8877
deployment:
  # Update CPU/Memory as needed
  resources:
    limits:
      cpu: 2
      memory: 10Gi
    requests:
      cpu: 1
      memory: 2Gi
  # Update to deploy multiple replicas of EG.
  replicas: 2
  # Give Enteprise Gateway some time to gracefully shutdown
  terminationGracePeriodSeconds: 60

kip:
  enabled: false # turn this off, if running DaemonSets is restricted by your cluster Administrator

ingress:
  enabled: true
  # Ingress resource host
  hostName: "[unique-fully-qualified-domain-name]"

```
