### ISSUE TITLE
how to schedule gpu kernel to gpu node in k8s

### ISSUE THREAD

**Issue by SolarisYan** [jupyter/enterprise_gateway#424]
Hi there, i have a quesion about the gpu kernel like kubernetes-kernel-tf-py-gpu.
i want to use it for ai , but i'm not sure how k8s will to scheule it to a node with gpu. i have label the gpu node for type=gpu, how can i config it for k8s to schedule it to my gpu node.

Any one can help me? I would really appreciate.

**Comment by kevin-bates** [comment]
@SolarisYan - thank you for the issue.

Please note that support for Kubernetes is still under development and `kernel-pod.yaml` customization is one of the areas in which we feel should be addressed and is required for extensions like this.

Although I have not run with a gpu-configured kernel, a colleague has.  This required modification of the `kernel-pod.yaml` file.  Since we use the same kernel-pod.yaml to launch all k8s kernels, this can be a bit unwieldy at the moment.  That said, here is the modified kernel-pod.yaml used for that.
```
apiVersion: v1
kind: Pod
metadata:
  name: $kernel_username-$kernel_id
  namespace: $namespace
  labels:
    kernel_id: $kernel_id
    app: enterprise-gateway
    component: kernel
  annotations:
    scheduler.alpha.kubernetes.io/nvidiaGPU: '{ "AllocationPriority": "Dense" }'
    scheduler.alpha.kubernetes.io/tolerations: '[ { "key": "dedicated", "operator": "Equal", "value": "gpu-task" } ]'
spec:
  restartPolicy: Never
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: gpu-task
  containers:
  - env:
    - name: EG_RESPONSE_ADDRESS
      value: $response_address
    - name: KERNEL_CONNECTION_FILENAME
      value: $connection_filename
    - name: KERNEL_LANGUAGE
      value: $language
    - name: KERNEL_SPARK_CONTEXT_INIT_MODE
      value: $spark_context_init_mode
    - name: KERNEL_USERNAME
      value: $kernel_username
    - name: KERNEL_ID
      value: $kernel_id
    - name: KERNEL_NAMESPACE
      value: $namespace
    image: $docker_image
    name: $kernel_username-$kernel_id
    command: ["/etc/bootstrap-kernel.sh"]
    nodeSelector:
      ibm-cloud.kubernetes.io/gpu-type: nvidia-TeslaK80
    resources:
      limits:
        alpha.kubernetes.io/nvidia-gpu: "1"
        cpu: "4"
        memory: 25165824k
      requests:
        alpha.kubernetes.io/nvidia-gpu: "1"
        cpu: "4"
        memory: 25165824k
```
Note the _annotations_, _tolerations_, _nodeSelector_, and _resources_ additions.  Also, we've placed curly braces `{}` around the parameter names since then.

I hope this helps.
