### ISSUE TITLE
Kubernetes ingress

### ISSUE THREAD

**Issue by witten** [jupyter/enterprise_gateway#626]
Based on the [documentation](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started-kubernetes.html#enterprise-gateway-deployment), it sounds like the current approach for reaching the Jupyter Enterprise Gateway running on Kubernetes is via a NodePort. However, on most clusters, this does not actually make the port available to the outside world, but rather just to internal cluster IPs.

So this ticket is a request to add support for including an optional [Kubernetes Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) resource when deploying Jupyter Enterprise Gateway. The idea is that if the cluster is configured for ingress, then the Ingress resource will thereby make the Gateway accessible from the outside world. This makes it much more convenient to reach the Gateway, say from a developer's local laptop. (Without ingress, a developer may need to maintain a `kubectl port-forward` proxy or similar.)

Note that making ingress optional may be easier to do once a Helm chart is available (#625).

**Comment by lresende** [comment]
You can find an ingress template at our [ansible scripts](https://github.com/lresende/ansible-kubernetes-cluster/blob/master/roles/jupyter-enterprise-gateway/templates/enterprise-gateway-ingress.yaml.j2). The issue that I see with providing the yaml at eg repo is that there are different versions of ingress implementations and from playing with couple ones they all require different configurations and I don't think we can easily maintain/test on the multiple available ingress implementations, but I am open to suggestions... maybe just add this example to the documentation and users would translate/configure based on the ingress they are using ?

**Comment by witten** [comment]
One way I've seen around this, besides making ingress itself optional, is to support configurable ingress annotation keys/values. Here's an example of an arbitrary Helm template that takes this approach: https://github.com/helm/charts/blob/master/incubator/istio/templates/deployment/ingress.yaml .. Note the `.Values.ingress.annotations` that are injected into the template.

That way, it's up to the user deploying (in this case, deploying the Helm chart) to make the Ingress resource work with their own ingress implementation.

But you make a fair point that maybe it's not worth trying to make this work for the variety of ingress implementations. As soon as you support Ingress resources, the next request will be for Certificate resources.. Documentation examples may be sufficient, especially if there's a base Helm chart (as per #625) that users can derive from to add their own custom resources like Ingresses and Certificates.

**Comment by witten** [comment]
Some additional thoughts from @kevin-bates on the topic of ingress from #625:

> Also, in working with this, I found the k8s-master-ip thing to be virtually useless unless you're in a single-node env (for POCs, etc.). As a result, I'm thinking it would be really helpful if we could add a template (in another PR), that produces the equivalent of what our [ansible scripts produce for a traefik ingress](https://github.com/lresende/ansible-kubernetes-cluster/blob/3c2f5386c84771a2e788f3cf6e29ac26b6e58a86/roles/jupyter-enterprise-gateway/templates/enterprise-gateway-ingress.yaml.j2). Of course, we'd want to make the ingress 'provider' a variable, along with the path (which is likely a provider-specific variable). But I see that as another great thing to add from an example standpoint for others to glean from.

**Comment by lresende** [comment]
Here is an example using Traefik:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: enterprise-gateway
  name: enterprise-gateway-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: {{ groups['master'][0] }}.{{ ansible_domain }}
    http:
      paths:
      - path: /gateway
        backend:
          serviceName: enterprise-gateway
servicePort: 8888
```

Here is an example using Nginx
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: enterprise-gateway
  name: enterprise-gateway-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: false
    nginx.ingress.kubernetes.io/force-ssl-redirect: false
spec:
  rules:
  - host:
    http:
      paths:
      - path: /gateway/?(.*)
        backend:
          serviceName: enterprise-gateway
          servicePort: 8888
```
