### ISSUE TITLE
Pass credentials into notebooks

### ISSUE THREAD

**Issue by witten** [jupyter/enterprise_gateway#642]
Not sure if this is a support request or a feature request. Here's my use case: As a dev, I want to create a Jupyter notebook and check it into source control and maybe even share it with other devs. With Enterprise Gateway running on a cluster, and Jupyter running locally on my laptop, this is easy to do. The difficulty arises as soon as I want to access a credentialed resource from within my notebook. For instance, let's say that I want to read some data via Spark from AWS S3, and I want to supply my own credentials when doing so.

I don't want to hard-code my personal S3 credentials into my notebook, because I really shouldn't check them into source control nor share the notebook with other devs. The traditional solution to this sort of thing is to use local environment variables or something like [python-dotenv](https://github.com/theskumar/python-dotenv) to abstract the credentials outside of the notebook. However, because the notebook is running remotely, and because Enterprise Gateway doesn't plumb though local environment variables all the way to the remotely running notebook (as far as I can tell), I haven't found a way to plumb through credentials or other local values.

I have looked at the `os.environ` available to me in the notebook on the hope that I could pass in arbitrary `KERNEL_*`-prefixed environment variables. However, the only such environment variable that shows up within the notebook is `KERNEL_LANGUAGE`.

Any ideas?

**Comment by lresende** [comment]
Any environment variables prefixed by KERNEL_ will flow all way to the kernels and KERNEL_LANGUAGE is just one example of it. More details are also documented in our [readthedocs.io page](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/config-options.html?highlight=KERNEL_).

**Comment by kevin-bates** [comment]
On Kubernetes, the _flow_ of `KERNEL_` are gated by what the pod exposes via kernel-pod.yaml - so you'd probably need to enable the flow accordingly.

Now that we have jinja template support, I suspect there's a way we could make the KERNEL envs more dynamic - but haven't gotten around to that.

**Comment by witten** [comment]
I'm not sure that `kernel-pod.yaml` is passing through all variables. For instance, I'm setting the following before running Jupyter locally:

```bash
export KG_URL=http://localhost:8888
export KG_HTTP_USER=guest
export KG_HTTP_PASS=guest-password
export KG_REQUEST_TIMEOUT=30
export KERNEL_USERNAME=${KG_HTTP_USER}
export KERNEL_NAMESPACE=test
export KERNEL_SERVICE_ACCOUNT_NAME=test-service-account
export KERNEL_S3_API_KEY=supersecret
```

And based on the `env:` in `kernel-pod.yaml.j2`, I would expect several of those to get passed through into the notebook:

```yaml
  - env:
    - name: EG_RESPONSE_ADDRESS
      value: "{{ eg_response_address }}"
    - name: KERNEL_LANGUAGE
      value: "{{ kernel_language }}"
    - name: KERNEL_SPARK_CONTEXT_INIT_MODE
      value: "{{ kernel_spark_context_init_mode }}"
    - name: KERNEL_NAME
      value: "{{ kernel_name }}"
    - name: KERNEL_USERNAME
      value: "{{ kernel_username }}"
    - name: KERNEL_ID
      value: "{{ kernel_id }}"
    - name: KERNEL_NAMESPACE
      value: "{{ kernel_namespace }}"
```

But in the notebook, this is all that shows up:

```python
In [2]: list(key for key in os.environ.keys() if key.startswith('KERNEL_'))
Out [2]: ['KERNEL_LANGUAGE']
```
