### ISSUE TITLE
/dev/shm shared memory expansion 

### ISSUE THREAD

**Issue by JorisJamers** [jupyter/enterprise_gateway#749]
We are trying to expand our shared memory `/dev/shm` in the kernel pods. In Kubernetes this can be done with the following mount : 

```
spec:
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  containers:
  - image: gcr.io/project/image
    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
``` 

When adding this to the jupyter enterprise gateway we also get an expansion on the shared memory inside of that pod. Now, I was wondering if it is possible to get this working in the Kernel pods as well. 

I have tried to add it in the `kernel-pod.yaml.j2` file hardcoded, but this does not work. I'm not 100% sure how that `launch_kubernetes.py` script works so I was wondering if anyone has ever done this?
