### ISSUE TITLE
Limits and Resource Quotas

### ISSUE THREAD

**Issue by kubernetian** [jupyter/enterprise_gateway#770]
Since updating the conditional volume mounts I have encountered a new issue. While having resource quotas and limits in any given namespace where the Enterprise Gateway is deployed. The EG and the Kernels are not spawning because the following specs are missing in the templates : 

kernel-pod.yaml.j2
```
    name: "{{ kernel_pod_name }}"
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
        nvidia.com/gpu: "0"
    {% if kernel_working_dir is defined %}
    workingDir: "{{ kernel_working_dir }}"
    {% endif %}
    volumeMounts:
```

Enterprise Gateway Deployment YAML snippet 
```
image: elyra/enterprise-gateway:dev
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
            nvidia.com/gpu: "0"
```

Image puller daemonset YAML snippet 
```
image: elyra/kernel-image-puller:dev
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
            nvidia.com/gpu: "0"
``` 

Basically in all the templates there is no definition for limits, this blocks the pods from spawning in a namespace where these limits and quotas are defined. 

I think this is something that can be catched with an Admission Controller, but might be a good idea to implement it in the templates? 

I'm not sure how to pass those variables, so in my own setup I hardcoded the limits in the templates. 

I browsed some issues but I don't think this is mentioned somewhere already? Correct me if I'm wrong @kevin-bates
