### ISSUE TITLE
How to spin up specific docker container using dockerspawner in docker hub

### ISSUE THREAD

**Issue by abinassahoo** [jupyter/enterprise_gateway#901]
## Description
Hi Team,
can anyone please help with any documentation for below use case.

I want to create a specific notebook server container (elyra/nb2kg) for each user to connect to my Enterprise Gateway from jupyter hub using dockerspawner. I followed the documentation [here](https://blog.jupyter.org/on-demand-notebooks-with-jupyterhub-jupyter-enterprise-gateway-and-kubernetes-e8e423695cbf) but this is using helm, whereas I wanted to do the solution using dockerspawner.

## Environment

- Enterprise Gateway Version 2.3.0.dev1
- Platform:  Docker
- Others : Jupyterhub 1.1.0

**Comment by kevin-bates** [comment]
A couple comments.
1. The NB2KG server extension is no longer necessary provided the version of notebook you're using is >= 6.0.  Instead, a gateway server can be accessed from Notebook simply by specifying the `--gateway-url <gateway-server-url>` option.
2. Because there is now only the single command-line option required to configure a notebook server to access EG, this exercise reduces to configuring the dockerspawner to launch a notebook server (with a particular option).  As a result, I would recommend consulting the Jupyter Hub dockerspawner documentation or open an issue there, since we (EG) are not familiar with dockerspawner specifics.

That said, I believe a good portion of the referenced blog post still applies.  For example, the following entry:
```
  extraEnv:
    KG_URL: <FQDN of Gateway Endpoint>
    KG_HTTP_USER: jovyan
    KERNEL_USERNAME: jovyan
    KG_REQUEST_TIMEOUT: 60
```
would be transposed to when using the gateway code now built into Notebook >= 6.0:
```
  extraEnv:
    JUPYTER_GATEWAY_URL: <FQDN of Gateway Endpoint>
    JUPYTER_GATEWAY_HTTP_USER: jovyan
    KERNEL_USERNAME: jovyan
    JUPYTER_GATEWAY_REQUEST_TIMEOUT: 60
```
