### ISSUE TITLE
support of submit spark k8s kernel with gcp spark operator

### ISSUE THREAD

**Issue by abzymeinsjtu** [jupyter/enterprise_gateway#984]
hi @kevin-bates kevin, is there any plan about submit spark k8s kernel with [gcp spark operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator), a popular k8s operator with a CRD including plenty feature of a spark application . 

p.s. i'm now working with the operator against aliyun EMR product, and i would be glad to contribute if possible.

**Comment by abzymeinsjtu** [comment]
it seems some change in [launch_kubernetes.py](https://github.com/jupyter/enterprise_gateway/blob/master/etc/kernel-launchers/kubernetes/scripts/launch_kubernetes.py) with a crd template will work

**Comment by kevin-bates** [comment]
Hi @abz53378 - I don't know anything about `gcp spark operator` but am glad you're able to move forward.  Do you think this might be something generally useful to others?  If so, perhaps you could provide a pull request.  Since I'm in the dark here, providing as much detail as possible would be helpful.  If this requires a completely separate script/template, then we'll need to figure out how to best make this work from the user's perspective.  Thanks.

**Comment by abzymeinsjtu** [comment]
you just include a wrong one huh, just call me Evans or Sun

generally speaking, it's a crd based k8s resource, you can just submit a spark by creating such kind of resource as below 

```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: jupyter-based-on-spark-operator-crd-{{ kernel_id }}
spec:
  type: Python
  pythonVersion: "3"
  sparkVersion: 2.4.5
  image: {{ kernel_image }}
  mainApplicationFile: "local:///tmp/launch_ipykernel.py"
  arguments:
    - "--RemoteProcessProxy.kernel-id"
    - "{{ kernel_id }}"
    - "--RemoteProcessProxy.spark-context-initialization-mode"
    - "{{ init_mode }}"
    - "--RemoteProcessProxy.response-address"
    - "{{ eg_response_address }}"
    - "--RemoteProcessProxy.port-range"
    - "{{ eg_port_range }}"
  driver:
    labels:
      kernel_id: "{{ kernel_id }}"
      app: enterprise-gateway
      component: kernel
    cores: 1
    coreLimit: 1000m
    memory: 1g
  executor:
    cores: 1
    coreLimit: 1000m
    memory: 1g
```

This is just a specific case of k8s crd. I can easily implement a spark operator based kernel, but maybe support for created crd based kernel will be generic
